config/routes.rb
Rails.application.routes.draw do

  root 'comparisons#index'

  get '/login' => 'sessions#new'
  get '/auth/github/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'comparisons/show' => 'comparisons#show', as: 'show_boroughs'
  resources 'boroughs', :only => [:show]
  resources 'search', :only => [:index]

  get '/hospitals/:id' => 'hospitals#show', as:'hospital'

  get '/communitygardens/:id' => 'community_gardens#show', as:'community_garden'

  get 'flus/:id' => 'flus#show', as:'flu'

  get 'districts/:id' => 'districts#show', as:'district'

  get 'farmersmarkets/:id' => 'farmers_markets#show', as:'farmers_market'

  delete 'favorites/:id' => 'favorites#destroy', as:'favorite'

  resources :users, :only => [:show]

  post '/favorites/create' => 'favorites#create'

end

app/models/borough.rb
# == Schema Information
#
# Table name: boroughs
#
#  id         :integer          not null, primary key
#  name       :string
#  area       :integer
#  population :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Borough < ActiveRecord::Base

  has_many :hospitals
  has_many :flus
  has_many :districts
  has_many :jobs
  has_many :farmers_markets
  has_many :community_gardens
  
  def population_density
    population/area
  end

  def hospital_count(normalizer)
    num_of_hospitals = hospitals.count.to_f
    normalizer != "nil" ? num_of_hospitals/self.send(normalizer) : num_of_hospitals
  end

  def farmers_market_count(normalizer)
    num_of_markets = farmers_markets.count.to_f
    normalizer != "nil" ? num_of_markets/self.send(normalizer) : num_of_markets
  end

  def flu_count(normalizer)
    num_of_flus = flus.count.to_f
    normalizer != "nil" ? num_of_flus/self.send(normalizer) : num_of_flus
  end

  def community_garden_count(normalizer)
    num_of_gardens = community_gardens.count.to_f
    normalizer != "nil" ? num_of_gardens/self.send(normalizer) : num_of_gardens
  end

  def district_attendance(normalizer)
    array = districts.map do |district|
      district.attendance
    end
    avg_attendance=(array.inject{ |sum, x| sum + x } / array.size).round(2)
    normalizer != "nil" ? avg_attendance/self.send(normalizer) : avg_attendance
  end
end

app/controllers/boroughs_controller.rb
class BoroughsController < ApplicationController

  def show
    @borough = Borough.find(params[:id])
  end 

end

app/helpers/boroughs_helper.rb
module BoroughsHelper
end

app/views/boroughs/_drop_down.html.erb
<%= form_tag('/boroughs/show', method: :get) %>  
<p>
<%= label_tag 'data1'%>
<%= select_tag :data_set_one, options_for_select([["Hospital Count", "hospital_count"], ["District Attendance","district_attendance"]])%>
</p>
<p>
<%= label_tag 'data2'%>
<%= select_tag :data_set_two, options_for_select([["Hospital Count", "hospital_count"], ["District Attendance","district_attendance"]])%>
</p>
<p>
<%= label_tag 'normalizer'%>
<%= select_tag :normalizer, options_for_select([["Population","population"], ["Area","area"], ["Population Density", "population_density"], ["None", "nil"]])%>
</p>
<%= submit_tag "Return"%>

app/views/boroughs/_links.html.erb
<h3>View statistics for each borough</h3>
<% @boroughs.each do |borough| %>
<p><%= link_to borough.name, borough_path(borough) %></p>
<% end %>

app/views/boroughs/index.html.erb
<h1>How does x correlate with y?</h1>
<p>
Our site simple takes in different data sets and allows you to compare them to each other to check for correlation. We hope you enjoy looking through this data as much as we do, but please remember that CORRELATION DOES NOT MEAN CAUSATION!
</p>
<!-- Start drop down menus here -->
<%= render partial: 'boroughs/drop_down.html.erb' %>
<!-- End drop down menus-->

app/views/boroughs/show.html.erb
<h3>Borough: <%= @borough.name %></h3>

<h4>Population: <%= @borough.population %></h4>

<h4>Area: <%= @borough.area %> square miles</h4>

<h4>Population Density: <%= @borough.population / @borough.area %> residents/square mile </h4>

<% borough_methods.each do |method| %>
<p><%= readable(method) %>: <%= @borough.send(method, 'nil') %></p>
<% end %>