config/routes.rb
Rails.application.routes.draw do

  root 'comparisons#index'

  get '/login' => 'sessions#new'
  get '/auth/github/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'comparisons/show' => 'comparisons#show', as: 'show_boroughs'
  resources 'boroughs', :only => [:show]
  resources 'search', :only => [:index]

  get '/hospitals/:id' => 'hospitals#show', as:'hospital'

  get '/communitygardens/:id' => 'community_gardens#show', as:'community_garden'

  get 'flus/:id' => 'flus#show', as:'flu'

  get 'districts/:id' => 'districts#show', as:'district'

  get 'farmersmarkets/:id' => 'farmers_markets#show', as:'farmers_market'

  delete 'favorites/:id' => 'favorites#destroy', as:'favorite'

  resources :users, :only => [:show]

  post '/favorites/create' => 'favorites#create'

end

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="col-md-1"></div>

  <div class="col-md-10"><h2><center>The Five Boroughs</center></h2></div>

  <div class="col-md-1"></div>
</div>

<div class="row">
  <div class="col-md-1"></div>
  <% Borough.all.each do |borough|%>
    <div class="col-md-2">
      <h3><%= link_to borough.name, borough %></h3>
    </div>
  <% end %>
  <div class="col-md-1"></div>
</div>

app/views/layouts/_login.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-3">
    <h2><%= link_to "Home", root_path %> | <%= link_to 'Back', :back %></h2>
  </div>
  

      <% if logged_in? %>
        <div class="col-md-4"><center>
          <h3>Logged in as: <%= link_to current_user.name, user_path(current_user) %></h3>
        </center></div>
        <div class="col-md-3"><center>
          <h3><%= link_to 'Log Out', logout_path %></h3>
        </center></div>
      <% else %>
        <div class="col-md-7">
          <center>
            <h3><%= link_to 'Log In with Github', login_path %></h3>
          </center>
        </div>
      <% end %>


  <div class="col-md-1"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectHam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'layouts/login.html.erb'%>

<%= yield %>
<%= render partial: 'layouts/footer.html.erb'%>

</body>
</html>